### ISSUE TITLE
Missing 'ddev-get` topic

### ISSUE THREAD

**Issue by tyler36** [skeemer/ddev-wkhtmltox#4]
Thanks for creating the addon.

At the moment, its not showing up in my list when I run: `ddev get --list --all`.
I think this is beacuse it's missing the `ddev-get` topic tag.

## Fix

1. On the project home page, click the cogs next to "About" in the sidebar.
2. Under topics, add "ddev-get". It will immediately be added to the list provided by `ddev get --list --all`.

Adding this will help others discover the addon.

**Comment by skeemer** [comment]
Added and description set.

**Comment by tyler36** [comment]
Thank you. 

Can confirm the addon appears in the list.
